// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nexus.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Nexus.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260410214347_UseXminForConcurrency")]
    partial class UseXminForConcurrency
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Nexus.Domain.Entities.Agency", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Abn")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("abn");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LicenseNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("license_number");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone_number");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("website_url");

                    b.HasKey("Id")
                        .HasName("pk_agencies");

                    b.HasIndex("Abn")
                        .IsUnique()
                        .HasDatabaseName("ix_agencies_abn");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_agencies_name");

                    b.ToTable("agencies", (string)null);
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Agent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AgencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("agency_id");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("LicenseNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("license_number");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone_number");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("photo_url");

                    b.Property<string>("PositionTitle")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("position_title");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_agents");

                    b.HasIndex("AgencyId")
                        .HasDatabaseName("ix_agents_agency_id");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_agents_email");

                    b.ToTable("agents", (string)null);
                });

            modelBuilder.Entity("Nexus.Domain.Entities.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChatSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("chat_session_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<string>("ToolName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tool_name");

                    b.HasKey("Id")
                        .HasName("pk_chat_messages");

                    b.HasIndex("ChatSessionId")
                        .HasDatabaseName("ix_chat_messages_chat_session_id");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("ix_chat_messages_created_at_utc");

                    b.HasIndex("Role")
                        .HasDatabaseName("ix_chat_messages_role");

                    b.HasIndex("ChatSessionId", "CreatedAtUtc")
                        .HasDatabaseName("ix_chat_messages_chat_session_id_created_at_utc");

                    b.ToTable("chat_messages", (string)null);
                });

            modelBuilder.Entity("Nexus.Domain.Entities.ChatSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("EndedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at_utc");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_chat_sessions");

                    b.HasIndex("StartedAtUtc")
                        .HasDatabaseName("ix_chat_sessions_started_at_utc");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_chat_sessions_user_id");

                    b.ToTable("chat_sessions", (string)null);
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Deposit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("currency");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid")
                        .HasColumnName("listing_id");

                    b.Property<Guid?>("ListingId1")
                        .HasColumnType("uuid")
                        .HasColumnName("listing_id1");

                    b.Property<DateTimeOffset?>("PaidAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at_utc");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<Guid?>("PropertyId1")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id1");

                    b.Property<string>("RawResponse")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_response");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("StripePaymentIntentId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("stripe_payment_intent_id");

                    b.Property<string>("StripeSessionId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("stripe_session_id");

                    b.Property<string>("StripeSessionUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("stripe_session_url");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid?>("UserId1")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id1");

                    b.HasKey("Id")
                        .HasName("pk_deposits");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_deposits_idempotency_key");

                    b.HasIndex("ListingId")
                        .HasDatabaseName("ix_deposits_listing_id");

                    b.HasIndex("ListingId1")
                        .HasDatabaseName("ix_deposits_listing_id1");

                    b.HasIndex("PropertyId")
                        .HasDatabaseName("ix_deposits_property_id");

                    b.HasIndex("PropertyId1")
                        .HasDatabaseName("ix_deposits_property_id1");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_deposits_status");

                    b.HasIndex("StripeSessionId")
                        .IsUnique()
                        .HasDatabaseName("ix_deposits_stripe_session_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_deposits_user_id");

                    b.HasIndex("UserId1")
                        .HasDatabaseName("ix_deposits_user_id1");

                    b.ToTable("deposits", (string)null);
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Enquiry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("ListingId")
                        .HasColumnType("uuid")
                        .HasColumnName("listing_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("message");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<DateTimeOffset?>("RespondedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("responded_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_enquiries");

                    b.HasIndex("AgentId")
                        .HasDatabaseName("ix_enquiries_agent_id");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("ix_enquiries_created_at_utc");

                    b.HasIndex("ListingId")
                        .HasDatabaseName("ix_enquiries_listing_id");

                    b.HasIndex("PropertyId")
                        .HasDatabaseName("ix_enquiries_property_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_enquiries_status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_enquiries_user_id");

                    b.ToTable("enquiries", (string)null);
                });

            modelBuilder.Entity("Nexus.Domain.Entities.InspectionBooking", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("InspectionSlotId")
                        .HasColumnType("uuid")
                        .HasColumnName("inspection_slot_id");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid")
                        .HasColumnName("listing_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_inspection_bookings");

                    b.HasIndex("AgentId")
                        .HasDatabaseName("ix_inspection_bookings_agent_id");

                    b.HasIndex("ListingId")
                        .HasDatabaseName("ix_inspection_bookings_listing_id");

                    b.HasIndex("PropertyId")
                        .HasDatabaseName("ix_inspection_bookings_property_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_inspection_bookings_status");

                    b.HasIndex("InspectionSlotId", "Status")
                        .HasDatabaseName("ix_inspection_bookings_inspection_slot_id_status");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("ix_inspection_bookings_user_id_status");

                    b.ToTable("inspection_bookings", (string)null);
                });

            modelBuilder.Entity("Nexus.Domain.Entities.InspectionSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_id");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset>("EndAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_at_utc");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid")
                        .HasColumnName("listing_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<DateTimeOffset>("StartAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_inspection_slots");

                    b.HasIndex("AgentId")
                        .HasDatabaseName("ix_inspection_slots_agent_id");

                    b.HasIndex("ListingId")
                        .HasDatabaseName("ix_inspection_slots_listing_id");

                    b.HasIndex("PropertyId")
                        .HasDatabaseName("ix_inspection_slots_property_id");

                    b.HasIndex("StartAtUtc")
                        .HasDatabaseName("ix_inspection_slots_start_at_utc");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_inspection_slots_status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_inspection_slots_user_id");

                    b.HasIndex("AgentId", "StartAtUtc")
                        .HasDatabaseName("ix_inspection_slots_agent_id_start_at_utc");

                    b.HasIndex("ListingId", "StartAtUtc")
                        .HasDatabaseName("ix_inspection_slots_listing_id_start_at_utc");

                    b.HasIndex("PropertyId", "StartAtUtc")
                        .HasDatabaseName("ix_inspection_slots_property_id_start_at_utc");

                    b.HasIndex("Status", "StartAtUtc")
                        .HasDatabaseName("ix_inspection_slots_status_start_at_utc");

                    b.ToTable("inspection_slots", null, t =>
                        {
                            t.HasCheckConstraint("CK_inspection_slots_capacity_positive", "capacity > 0");

                            t.HasCheckConstraint("CK_inspection_slots_end_after_start", "end_at_utc > start_at_utc");
                        });
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Listing", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AgencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("agency_id");

                    b.Property<Guid?>("AgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_id");

                    b.Property<DateTimeOffset?>("AvailableFromUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_from_utc");

                    b.Property<DateTimeOffset?>("ClosedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_published");

                    b.Property<DateTimeOffset>("ListedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("listed_at_utc");

                    b.Property<string>("ListingType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("listing_type");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_listings");

                    b.HasIndex("AgencyId")
                        .HasDatabaseName("ix_listings_agency_id");

                    b.HasIndex("AgentId")
                        .HasDatabaseName("ix_listings_agent_id");

                    b.HasIndex("IsPublished")
                        .HasDatabaseName("ix_listings_is_published");

                    b.HasIndex("ListedAtUtc")
                        .HasDatabaseName("ix_listings_listed_at_utc");

                    b.HasIndex("ListingType")
                        .HasDatabaseName("ix_listings_listing_type");

                    b.HasIndex("PropertyId")
                        .HasDatabaseName("ix_listings_property_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_listings_status");

                    b.ToTable("listings", (string)null);
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Currency")
                        .HasColumnType("integer")
                        .HasColumnName("currency");

                    b.Property<string>("FrontendIdempotencyKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("frontend_idempotency_key");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("total_amount");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("Nexus.Domain.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("integer")
                        .HasColumnName("order_id");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("product_name");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("pk_order_items");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_order_items_order_id");

                    b.ToTable("order_items", (string)null);
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<string>("BackendIdempotencyKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("backend_idempotency_key");

                    b.Property<decimal>("CapturedAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("captured_amount");

                    b.Property<DateTimeOffset?>("CapturedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Currency")
                        .HasColumnType("integer")
                        .HasColumnName("currency");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer")
                        .HasColumnName("order_id");

                    b.Property<int>("Provider")
                        .HasColumnType("integer")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderCaptureId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider_capture_id");

                    b.Property<string>("ProviderOrderId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider_order_id");

                    b.Property<string>("RawResponse")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_response");

                    b.Property<decimal>("RefundedAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("refunded_amount");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_payments");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasDatabaseName("ix_payments_order_id");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Property", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AgencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("agency_id");

                    b.Property<Guid?>("AgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_id");

                    b.Property<int>("Bathrooms")
                        .HasColumnType("integer")
                        .HasColumnName("bathrooms");

                    b.Property<int>("Bedrooms")
                        .HasColumnType("integer")
                        .HasColumnName("bedrooms");

                    b.Property<decimal?>("BuildingSizeSqm")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("building_size_sqm");

                    b.Property<int>("CarSpaces")
                        .HasColumnType("integer")
                        .HasColumnName("car_spaces");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<decimal?>("LandSizeSqm")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("land_size_sqm");

                    b.Property<int>("PropertyTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("property_type_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<int?>("YearBuilt")
                        .HasColumnType("integer")
                        .HasColumnName("year_built");

                    b.HasKey("Id")
                        .HasName("pk_properties");

                    b.HasIndex("AgencyId")
                        .HasDatabaseName("ix_properties_agency_id");

                    b.HasIndex("AgentId")
                        .HasDatabaseName("ix_properties_agent_id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_properties_is_active");

                    b.HasIndex("PropertyTypeId")
                        .HasDatabaseName("ix_properties_property_type_id");

                    b.ToTable("properties", (string)null);
                });

            modelBuilder.Entity("Nexus.Domain.Entities.PropertyAddress", b =>
                {
                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address_line1");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address_line2");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("country");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("longitude");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("postcode");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("state");

                    b.Property<string>("Suburb")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("suburb");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("PropertyId")
                        .HasName("pk_property_addresses");

                    b.HasIndex("Postcode")
                        .HasDatabaseName("ix_property_addresses_postcode");

                    b.HasIndex("State")
                        .HasDatabaseName("ix_property_addresses_state");

                    b.HasIndex("Suburb")
                        .HasDatabaseName("ix_property_addresses_suburb");

                    b.ToTable("property_addresses", (string)null);
                });

            modelBuilder.Entity("Nexus.Domain.Entities.PropertyImage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Caption")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("caption");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_property_images");

                    b.HasIndex("PropertyId")
                        .IsUnique()
                        .HasDatabaseName("ux_property_images_primary_per_property")
                        .HasFilter("is_primary = true");

                    b.HasIndex("PropertyId", "DisplayOrder")
                        .IsUnique()
                        .HasDatabaseName("ux_property_images_property_id_display_order");

                    b.ToTable("property_images", (string)null);
                });

            modelBuilder.Entity("Nexus.Domain.Entities.PropertyType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_property_types");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_property_types_name");

                    b.ToTable("property_types", (string)null);
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Refund", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<string>("BackendIdempotencyKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("backend_idempotency_key");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("PaymentId")
                        .HasColumnType("integer")
                        .HasColumnName("payment_id");

                    b.Property<int>("Provider")
                        .HasColumnType("integer")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderRefundId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider_refund_id");

                    b.Property<string>("RawResponse")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_response");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_refund");

                    b.HasIndex("PaymentId")
                        .HasDatabaseName("ix_refund_payment_id");

                    b.ToTable("refund", (string)null);
                });

            modelBuilder.Entity("Nexus.Domain.Entities.SavedProperty", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<DateTimeOffset>("SavedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("saved_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_saved_properties");

                    b.HasIndex("PropertyId")
                        .HasDatabaseName("ix_saved_properties_property_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_saved_properties_user_id");

                    b.HasIndex("UserId", "PropertyId")
                        .IsUnique()
                        .HasDatabaseName("ix_saved_properties_user_id_property_id");

                    b.ToTable("saved_properties", (string)null);
                });

            modelBuilder.Entity("Nexus.Domain.Entities.ToolExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChatMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("chat_message_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<string>("InputJson")
                        .HasColumnType("text")
                        .HasColumnName("input_json");

                    b.Property<string>("OutputJson")
                        .HasColumnType("text")
                        .HasColumnName("output_json");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean")
                        .HasColumnName("success");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tool_name");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_tool_executions");

                    b.HasIndex("ChatMessageId")
                        .HasDatabaseName("ix_tool_executions_chat_message_id");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("ix_tool_executions_created_at_utc");

                    b.HasIndex("Success")
                        .HasDatabaseName("ix_tool_executions_success");

                    b.HasIndex("ToolName")
                        .HasDatabaseName("ix_tool_executions_tool_name");

                    b.ToTable("tool_executions", (string)null);
                });

            modelBuilder.Entity("Nexus.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone_number");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Nexus.Domain.Entities.UserLogin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("provider_key");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_logins_user_id");

                    b.HasIndex("Provider", "ProviderKey")
                        .IsUnique()
                        .HasDatabaseName("ix_user_logins_provider_provider_key");

                    b.ToTable("user_logins", (string)null);
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Agent", b =>
                {
                    b.HasOne("Nexus.Domain.Entities.Agency", "Agency")
                        .WithMany("Agents")
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_agents_agencies_agency_id");

                    b.Navigation("Agency");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.ChatMessage", b =>
                {
                    b.HasOne("Nexus.Domain.Entities.ChatSession", "ChatSession")
                        .WithMany("Messages")
                        .HasForeignKey("ChatSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_chat_messages_chat_sessions_chat_session_id");

                    b.Navigation("ChatSession");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.ChatSession", b =>
                {
                    b.HasOne("Nexus.Domain.Entities.User", "User")
                        .WithMany("ChatSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_chat_sessions_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Deposit", b =>
                {
                    b.HasOne("Nexus.Domain.Entities.Listing", "Listing")
                        .WithMany()
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_deposits_listings_listing_id");

                    b.HasOne("Nexus.Domain.Entities.Listing", null)
                        .WithMany("Deposits")
                        .HasForeignKey("ListingId1")
                        .HasConstraintName("fk_deposits_listings_listing_id1");

                    b.HasOne("Nexus.Domain.Entities.Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_deposits_properties_property_id");

                    b.HasOne("Nexus.Domain.Entities.Property", null)
                        .WithMany("Deposits")
                        .HasForeignKey("PropertyId1")
                        .HasConstraintName("fk_deposits_properties_property_id1");

                    b.HasOne("Nexus.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_deposits_users_user_id");

                    b.HasOne("Nexus.Domain.Entities.User", null)
                        .WithMany("Deposits")
                        .HasForeignKey("UserId1")
                        .HasConstraintName("fk_deposits_users_user_id1");

                    b.Navigation("Listing");

                    b.Navigation("Property");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Enquiry", b =>
                {
                    b.HasOne("Nexus.Domain.Entities.Agent", "Agent")
                        .WithMany("Enquiries")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_enquiries_agents_agent_id");

                    b.HasOne("Nexus.Domain.Entities.Listing", "Listing")
                        .WithMany("Enquiries")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_enquiries_listings_listing_id");

                    b.HasOne("Nexus.Domain.Entities.Property", "Property")
                        .WithMany("Enquiries")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_enquiries_properties_property_id");

                    b.HasOne("Nexus.Domain.Entities.User", "User")
                        .WithMany("Enquiries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_enquiries_users_user_id");

                    b.Navigation("Agent");

                    b.Navigation("Listing");

                    b.Navigation("Property");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.InspectionBooking", b =>
                {
                    b.HasOne("Nexus.Domain.Entities.Agent", "Agent")
                        .WithMany("InspectionBookings")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inspection_bookings_agents_agent_id");

                    b.HasOne("Nexus.Domain.Entities.InspectionSlot", "InspectionSlot")
                        .WithMany("InspectionBookings")
                        .HasForeignKey("InspectionSlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inspection_bookings_inspection_slots_inspection_slot_id");

                    b.HasOne("Nexus.Domain.Entities.Listing", "Listing")
                        .WithMany("InspectionBookings")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inspection_bookings_listings_listing_id");

                    b.HasOne("Nexus.Domain.Entities.Property", "Property")
                        .WithMany("InspectionBookings")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inspection_bookings_properties_property_id");

                    b.HasOne("Nexus.Domain.Entities.User", "User")
                        .WithMany("InspectionBookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inspection_bookings_users_user_id");

                    b.Navigation("Agent");

                    b.Navigation("InspectionSlot");

                    b.Navigation("Listing");

                    b.Navigation("Property");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.InspectionSlot", b =>
                {
                    b.HasOne("Nexus.Domain.Entities.Agent", "Agent")
                        .WithMany("InspectionSlots")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inspection_slots_agents_agent_id");

                    b.HasOne("Nexus.Domain.Entities.Listing", "Listing")
                        .WithMany("InspectionSlots")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inspection_slots_listings_listing_id");

                    b.HasOne("Nexus.Domain.Entities.Property", "Property")
                        .WithMany("InspectionSlots")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inspection_slots_properties_property_id");

                    b.HasOne("Nexus.Domain.Entities.User", "User")
                        .WithMany("CreatedSlots")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inspection_slots_users_user_id");

                    b.Navigation("Agent");

                    b.Navigation("Listing");

                    b.Navigation("Property");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Listing", b =>
                {
                    b.HasOne("Nexus.Domain.Entities.Agency", "Agency")
                        .WithMany("Listings")
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_listings_agencies_agency_id");

                    b.HasOne("Nexus.Domain.Entities.Agent", "Agent")
                        .WithMany("Listings")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_listings_agents_agent_id");

                    b.HasOne("Nexus.Domain.Entities.Property", "Property")
                        .WithMany("Listings")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_listings_properties_property_id");

                    b.Navigation("Agency");

                    b.Navigation("Agent");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("Nexus.Domain.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_items_orders_order_id");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Payment", b =>
                {
                    b.HasOne("Nexus.Domain.Entities.Order", "Order")
                        .WithOne("Payment")
                        .HasForeignKey("Nexus.Domain.Entities.Payment", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_payments_orders_order_id");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Property", b =>
                {
                    b.HasOne("Nexus.Domain.Entities.Agency", "Agency")
                        .WithMany()
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_properties_agencies_agency_id");

                    b.HasOne("Nexus.Domain.Entities.Agent", "Agent")
                        .WithMany("Properties")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_properties_agents_agent_id");

                    b.HasOne("Nexus.Domain.Entities.PropertyType", "PropertyType")
                        .WithMany("Properties")
                        .HasForeignKey("PropertyTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_properties_property_types_property_type_id");

                    b.Navigation("Agency");

                    b.Navigation("Agent");

                    b.Navigation("PropertyType");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.PropertyAddress", b =>
                {
                    b.HasOne("Nexus.Domain.Entities.Property", "Property")
                        .WithOne("Address")
                        .HasForeignKey("Nexus.Domain.Entities.PropertyAddress", "PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_property_addresses_properties_property_id");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.PropertyImage", b =>
                {
                    b.HasOne("Nexus.Domain.Entities.Property", "Property")
                        .WithMany("Images")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_property_images_properties_property_id");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Refund", b =>
                {
                    b.HasOne("Nexus.Domain.Entities.Payment", "Payment")
                        .WithMany("Refunds")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refund_payments_payment_id");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.SavedProperty", b =>
                {
                    b.HasOne("Nexus.Domain.Entities.Property", "Property")
                        .WithMany("SavedByUsers")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_saved_properties_properties_property_id");

                    b.HasOne("Nexus.Domain.Entities.User", "User")
                        .WithMany("SavedProperties")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_saved_properties_users_user_id");

                    b.Navigation("Property");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.ToolExecution", b =>
                {
                    b.HasOne("Nexus.Domain.Entities.ChatMessage", "ChatMessage")
                        .WithMany("ToolExecutions")
                        .HasForeignKey("ChatMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tool_executions_chat_messages_chat_message_id");

                    b.Navigation("ChatMessage");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.UserLogin", b =>
                {
                    b.HasOne("Nexus.Domain.Entities.User", "User")
                        .WithMany("Logins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_logins_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Agency", b =>
                {
                    b.Navigation("Agents");

                    b.Navigation("Listings");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Agent", b =>
                {
                    b.Navigation("Enquiries");

                    b.Navigation("InspectionBookings");

                    b.Navigation("InspectionSlots");

                    b.Navigation("Listings");

                    b.Navigation("Properties");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.ChatMessage", b =>
                {
                    b.Navigation("ToolExecutions");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.ChatSession", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.InspectionSlot", b =>
                {
                    b.Navigation("InspectionBookings");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Listing", b =>
                {
                    b.Navigation("Deposits");

                    b.Navigation("Enquiries");

                    b.Navigation("InspectionBookings");

                    b.Navigation("InspectionSlots");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Order", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Payment")
                        .IsRequired();
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Payment", b =>
                {
                    b.Navigation("Refunds");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Property", b =>
                {
                    b.Navigation("Address");

                    b.Navigation("Deposits");

                    b.Navigation("Enquiries");

                    b.Navigation("Images");

                    b.Navigation("InspectionBookings");

                    b.Navigation("InspectionSlots");

                    b.Navigation("Listings");

                    b.Navigation("SavedByUsers");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.PropertyType", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.User", b =>
                {
                    b.Navigation("ChatSessions");

                    b.Navigation("CreatedSlots");

                    b.Navigation("Deposits");

                    b.Navigation("Enquiries");

                    b.Navigation("InspectionBookings");

                    b.Navigation("Logins");

                    b.Navigation("SavedProperties");
                });
#pragma warning restore 612, 618
        }
    }
}
